development:
  adapter: mysql
  database: MyAdLounge_development
  username: root
  password: Neha
  host: localhost

test:
 adapter: mysql
 database: MyAdLounge_test
 username: root
 password: Neha
 host: localhost

production:
 adapter: mysql
 database: MyAdLounge_production
 username: root
 password: Neha
 host: localhost